### ISSUE TITLE
before, after, beforEach and afterEach examples in the readme

### ISSUE THREAD

**Issue by kedziorm** [rlgomes/pocha#17]
As I could see `before` and `after` was implemented (https://github.com/rlgomes/pocha/issues/3), but there are no examples of usage in the readme file.
I've tried to use them in my code, but I receive an error. Thus, I would like to ensure whether I use them incorrectly.

**Comment by rlgomes** [comment]
@kedziorm a quick example from the unit tests https://github.com/rlgomes/pocha/blob/master/test/input/multiple_its_with_before_failure.py I'll look at adding details to the README on the weekend when I have sometime.. Thanks for the report!

**Comment by kedziorm** [comment]
@rlgomes Sorry for lack of response and thank you for providing explanation / adding it to the Readme.
I noticed that I need to add `global` keyword to each variable that I include in the `before` hook to make it visible in test cases that are executed after `before`. Is it expected behavior?

**Comment by rlgomes** [comment]
Yes right now if you wanted to share something from the before hook to the tests or after hook itself you'd have to use a global variable. I think we could introduce the notion of a"pocha test context" which would be a keyword argument (so its optional) passed to any method decorated with `@before`, `@after`, `@it` and you could do something like:

```
@before
def init(context):
  context.server = ...

@describe('this is my test suite')
def _():
  @it('this test makes sure the server responds to ping')
  def _(context):
    assert context.server.ping()
...

@after
def clean_up(context):
  context.server.shutdown()
```

Something like that would avoid globals. What do you think ?

**Comment by kedziorm** [comment]
Yes, this looks good.
However, I wonder how it will behave in case of the embeded `before` and
`after` blocks. Let me provide an example:

@describe(....)

   @before
   ...

   @describe(...)

      @before
      ...

      it(...)



niedz., 8.04.2018, 17:27 użytkownik Rodney Lopes Gomes <
notifications@github.com> napisał:

**Comment by rlgomes** [comment]
Since I like to make sure things are always done with the least amount of surprises. I'd want the context within the @describe for the @before would be unique to that describe and outside of the @describe scope that context and even that before shouldn't exist. I'm not even sure right now if the nested before's behave that way so this could be a bug I need to fix. Give me a day or two to think about the `@before/@after` scope and making sure that behaves correctly and then I can also add the notion of a context that would be global to a python file if you defined at the top level (ie outside @describe) but would be scoped to the @describe block if you defined it in there and to all underlying @describe/@it blocks. I don't think this would actually be too hard but I just need to find a little time to fiddle with it.
